// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7qliBe7k9XBJW6zmDuc7oyesW7sxd_j8',
    appId: '1:580283806746:web:c9506e84e8d4897df1cda3',
    messagingSenderId: '580283806746',
    projectId: 'csen268-f24-g5',
    authDomain: 'csen268-f24-g5.firebaseapp.com',
    storageBucket: 'csen268-f24-g5.firebasestorage.app',
    measurementId: 'G-LRJXPTZVSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4pPAIddSaa9SGPbodriqH-KyyLovfFRQ',
    appId: '1:580283806746:android:b0204d27ae0f1099f1cda3',
    messagingSenderId: '580283806746',
    projectId: 'csen268-f24-g5',
    storageBucket: 'csen268-f24-g5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIraLiDmL9YI8HoFQ_HwNHCJIHHd7KKe8',
    appId: '1:580283806746:ios:f8e59660f1e849f7f1cda3',
    messagingSenderId: '580283806746',
    projectId: 'csen268-f24-g5',
    storageBucket: 'csen268-f24-g5.firebasestorage.app',
    iosBundleId: 'com.csen268.f24.g5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIraLiDmL9YI8HoFQ_HwNHCJIHHd7KKe8',
    appId: '1:580283806746:ios:204e1f5a79ec6ab3f1cda3',
    messagingSenderId: '580283806746',
    projectId: 'csen268-f24-g5',
    storageBucket: 'csen268-f24-g5.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7qliBe7k9XBJW6zmDuc7oyesW7sxd_j8',
    appId: '1:580283806746:web:47c2ee0d0021c318f1cda3',
    messagingSenderId: '580283806746',
    projectId: 'csen268-f24-g5',
    authDomain: 'csen268-f24-g5.firebaseapp.com',
    storageBucket: 'csen268-f24-g5.firebasestorage.app',
    measurementId: 'G-F0073FSHD5',
  );
}
